### ISSUE TITLE
500 when accessible printable versions of lessons on production

### ISSUE THREAD

**Issue by vbrown608** [EFForg/sec#201]

**Comment by wioux** [comment]
I disabled pdf generation since we were getting sporadic errors. 

https://github.com/EFForg/sec/blob/37533676d5b73e1cff1b9d8aa4b755c5cccd4755/app/models/lesson.rb#L49-L51

They might be fixed now so we could uncomment that and see what happens. We'll also need to add a delayed job worker to the production env à la

https://github.com/EFForg/sec/blob/d927d10e7aaf8cdcfcad409e9aaa3135bd74507d/docker-compose.yml.example#L54-L65

**Comment by wioux** [comment]
Hopefully fixed the issue in ba638103d943b91453372030ff3c208a7a01ee2e.
